# Uncomment this line to define a global platform for your project
 platform :ios, '11.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'SpokeStack' do

  pod 'googleapis', :path => '.'

end


