# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run XCode tests"
  lane :test do
    scan(workspace: "Spokestack.xcworkspace", scheme: "CircleCI", output_types: "html")
    # slack(message: "Yet another successful build of Spokestack-iOS")
  end
end
